[package]
name = "workshop"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = ">=2.6.3"
kill_switch = {git= "https://github.com/starknet-edu/kill-switch.git"}
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.14.0" }

[[target.starknet-contract]]
build-external-contracts = ["kill_switch::KillSwitch"]
sierra =true
casm = true

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.25.0" }

[scripts]
test= "snforge test"